name: Check Site Status

on:
  schedule:
    - cron: "*/5 * * * *" # setiap 5 menit
  workflow_dispatch: # agar bisa dijalankan manual dari GitHub UI

jobs:
  check-sites:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Setup repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ—ï¸ Install dependencies
        run: npm install

      - name: ğŸš€ Run Upptime status checks
        run: npx upptime check
        env:
          NOTIFICATION_EMAIL: true
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME_HERU }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD_HERU }}
